version: "3.9"

services:
  bagisto-app:
    build:
      context: ./bagisto
      dockerfile: Dockerfile
    container_name: bagisto-app
    environment:
      APP_NAME: "Bagisto"
      APP_ENV: "production"
      APP_KEY: ""
      APP_DEBUG: "false"
      APP_URL: "https://${SHOP_HOST}"
      DB_HOST: "db"
      DB_PORT: "3306"
      DB_DATABASE: "bagisto"
      DB_USERNAME: "bagisto"
      DB_PASSWORD: "${DB_PASSWORD}"
      CACHE_DRIVER: "redis"
      QUEUE_CONNECTION: "redis"
      SESSION_DRIVER: "redis"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
    volumes:
      - app_code:/var/www/html 
      - bagisto_storage:/var/www/html/storage
      - bagisto_uploads:/var/www/html/public/storage
    depends_on:
      - db
      - redis
    networks:
      - traefik_proxy
      - bagisto_net
    restart: unless-stopped

  web:
    image: nginx:alpine
    container_name: bagisto-web
    volumes:
      - app_code:/var/www/html:ro
      - ./nginx:/etc/nginx/conf.d:ro 
      - bagisto_uploads:/var/www/html/public/storage
    depends_on:
      - bagisto-app
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik_proxy
      - traefik.http.routers.shop.rule=Host("amas.amaslohaceposible.cloud")
      - traefik.http.routers.shop.entrypoints=websecure
      - traefik.http.routers.shop.tls.certresolver=le
      - traefik.http.services.shop.loadbalancer.server.port=80
    networks:
      - traefik_proxy
      - bagisto_net
    restart: unless-stopped

  db:
    image: mysql:8
    container_name: bagisto-db
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: "bagisto"
      MYSQL_USER: "bagisto"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - bagisto_net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-p${DB_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 3s
      retries: 30
      start_period: 20s

  redis:
    image: redis:alpine
    container_name: bagisto-redis
    networks:
      - bagisto_net
    restart: unless-stopped

  queue:
    depends_on:
      - bagisto-app
      - redis
    image: alpine:3.20
    container_name: bagisto-queue
    working_dir: /var/www/html
    command: sh -c "apk add --no-cache php82-cli php82-phar php82-openssl php82-redis && while true; do php artisan queue:work --tries=3 --sleep=3; done"
    volumes:
      - ./bagisto:/var/www/html
      - bagisto_storage:/var/www/html/storage
    networks:
      - bagisto_net
    restart: unless-stopped

volumes:
  app_code:
  db_data:
  bagisto_storage:
  bagisto_uploads:

networks:
  traefik_proxy:
    external: true
    name: traefik_proxy
  bagisto_net:
    driver: bridge
